print("Dame dos numeros")
num1 = input('Numero 1:')
num2 = input('Numero 2:')
res = int(num1) + int(num2)
print("La suma de {} + {} = {}".format(num1, num2, res))

print("Agrega un producto al carrito")
producto = input('Producto:')
precio = input('Precio:')
print("Producto: {} Precio: {}".format(producto, precio))
